#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
apt-get update
apt-get -y install nginx
echo 'Holberton School' > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server; rewrite ^/redirect_me https://findtheinvisiblecow.com permanent;' /etc/nginx/sites-available/default
service nginx start
