#!/usr/bin/env bash
# Installs and configures load balancer in nginx web server
sudo add-apt-repository ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get -y install haproxy
sed -i '/errorfile 504/afrontend Server\n\tbind :80\n\tmode http\n\tdefault_backend my_back' /etc/haproxy/haproxy.cfg
sed -i '/default_backend/abackend Nodes\n\tmode http\n\tbalance roundrobin\n\tserver 872-web-01 35.243.143.162:80 check\n\tserver 872-web-02 34.74.246.140:80 check' /etc/haproxy/haproxy.cfg
service haproxy start
