#!/usr/bin/env bash
# Installs and configures load balancer in nginx web server
apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.6
apt-get update
apt-get -y install haproxy=1.6.\*
echo "frontend server
        bind *:80
        mode http
        default_backend my_back" >> /etc/haproxy/haproxy.cfg
echo "backend my_back
        balance roundrobin
        server 872-web-01 35.243.143.162:80 check
        server 872-web-02 34.74.246.140:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy start
