#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely and ignores SIGTERM.
while ((1))
do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "I am invincible!!!"' SIGTERM
done
