#!/usr/bin/env bash
# Displays "bad luck", "good luck" and "Holberton School" on 3rd, 7th and the rest of iterations
i=0
while [ $i -lt 10 ]
do
    if [ $i -eq 3 ]
    then
        echo "bad luck"
    elif [ $i -eq 7 ]
    then
        echo "good luck"
    else
        echo "Holberton School"
    fi
        let i=$i+1
done