#!/usr/bin/env bash
# Displays "bad luck from China", "bad luck from Japan" and "bad luck from Italy" on 4th, 9th and 17th iterations, the rest is the index
i=1
while [ $i -le 20 ]
do
    case $i in
        4)
            echo $i
            echo "bad luck from China"
        ;;
        9)
            echo $i
            echo "bad luck from Japan"
        ;;
        17)
            echo $i
            echo "bad luck from Italy"
        ;;
        *)
            echo $i
        ;;
    esac
    i=$(( i + 1 ))
done
